#cloud-config
write_files:
  - path: /usr/local/share/ca-certificates/GoC-GdC-Root-A.crt
    permissions: '0644'
    content: |
      ${GoC-GdC-Root-A-crt}
  - path: /etc/environment
    permissions: '0644'
    content: |
      VSTS_AGENT_HTTP_CERT=/etc/ssl/certs/ca-certificates.crt
      NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
      REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
  - path: /usr/local/share/install_certificates.sh
    permissions: '7777'
    content: |
      ${install_certificates_sh}
  - path: /usr/local/share/install_java.sh
    permissions: '0755'
    content: |
      ${install_java_sh}
  - path: /usr/local/share/install_dotnet.sh
    permissions: '0755'
    content: |
      ${install_dotnet_sh}
  - path: /usr/local/share/install_powershell.sh
    permissions: '7777'
    content: |
      ${install_powershell_sh}
  - path: /usr/local/share/install_azure_cli.sh
    permissions: '7777'
    content: |
      ${install_azure_cli_sh}
  - path: /usr/local/share/install_terraform.sh
    permissions: '7777'
    content: |
      ${install_terraform_sh}
  - path: /usr/local/share/install_docker.sh
    permissions: '7777'
    content: |
      ${install_docker_sh}
  - path: /usr/local/share/install_nodejs.sh
    permissions: '7777'
    content: |
      ${install_nodejs_sh}
  - path: /usr/local/share/install_python.sh
    permissions: '7777'
    content: |
      ${install_python_sh}
  - path: /usr/local/share/install_checkov.sh
    permissions: '0755'
    content: |
      ${install_checkov_sh}
  - path: /usr/local/share/install_azure_functools.sh
    permissions: '7777'
    content: |
      ${install_azure_functools_sh}
  - path: /usr/local/share/update_motd.sh
    permissions: '7777'
    content: |
      ${install_motd_sh}

runcmd:
  - /usr/local/share/install_certificates.sh
  - /usr/local/share/install_powershell.sh
  - /usr/local/share/install_java.sh
  - /usr/local/share/install_dotnet.sh
  - /usr/local/share/install_azure_cli.sh
  - /usr/local/share/install_terraform.sh
  - /usr/local/share/install_docker.sh
  - /usr/local/share/install_nodejs.sh
  - /usr/local/share/install_python.sh
  - /usr/local/share/install_checkov.sh
  - /usr/local/share/install_azure_functools.sh
  - /usr/local/share/update_motd.sh
